#!/bin/bash
# Main parameters
export CW_OP_SEQUENCER_KEY="7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"
export CW_OP_SEQUENCER_ADDRESS="0x90F79bf6EB2c4f870365E785982E1f101E93b906"
export CW_OP_L1_RPC_URL="http://dockerhost:8333"
export CW_OP_L1_RPC_KIND="basic" # Available options are: alchemy, quicknode, parity, nethermind, debug_geth, erigon, basic, and any
export CW_OP_BATCHER_KEY="5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
export CW_OP_PROPOSER_KEY="59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
export CW_OP_L2OOP_ADDRESS="0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9" # Address of the "L2OutputOracleProxy" contract on L1
export CW_OP_L1SBP_ADDRESS="0x0165878A594ca255338adfa4d48449f69242Eb8F" # Address of the "L1StandardBridgeProxy" contract on L1
export CW_OP_CONFIG_NAME="local-op-devnet"
export CW_OP_L2_NETWORK_ID=3007

# Docker images for node apps
export CW_OP_IMAGE_OP_NODE="zesgen/op-node:v1.1.3"
export CW_OP_IMAGE_OP_BATCHER="zesgen/op-batcher:v1.1.3"
export CW_OP_IMAGE_OP_PROPOSER="zesgen/op-proposer:v1.1.3"
export CW_OP_IMAGE_OP_GETH="zesgen/op-geth:v1.101106.0"

# P2P parameters
export CW_OP_P2P_PRIVATE_KEY_NODE1="d01aba27820aeeb60ead4aed481eb30107426c18fd2e3133f1abac8fcd570d01"
export CW_OP_P2P_PRIVATE_KEY_NODE2="d02aba27820aeeb60ead4aed481eb30107426c18fd2e3133f1abac8fcd570d02"
export CW_OP_P2P_PRIVATE_KEY_NODE3="d03aba27820aeeb60ead4aed481eb30107426c18fd2e3133f1abac8fcd570d03"
export CW_OP_P2P_ID_NODE1="16Uiu2HAmFj2KVQEQQtgURtJKSWUmCgRsgeGs4piWP1YCREe64VLZ"
export CW_OP_P2P_ID_NODE2="16Uiu2HAmMgZfTriZqMDDrHCUAibcaKyv8ByV8qWuSFXLpss8Rjxb"
export CW_OP_P2P_ID_NODE3="16Uiu2HAmDKq53ypBfPNfAnwKvKwxXWjmVZ2viQahhWaaGntEqtPC"